- hosts: all

  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_connection_timeout: 1000 
    ansible_winrm_operation_timeout_sec: 1000 
    ansible_winrm_read_timeout_sec: 1000

  tasks:

  - name: wait for system to become reachable over WinRM
    wait_for_connection:
      delay: 60
      sleep: 15
      timeout: 900

  - name: ping
    win_ping:

  - include: Chocolatey.yml

  # - include: SMB1.yml
  # - include: InstallUpdates.yml